version: '3.9'

volumes:
  shared_data:

services:
  # This service has Docker's defualt user.
  # Which mean this container is used to update node modules.
  course_authoring_modules:
    build:
      context: .
      dockerfile: ./.docker/course-authoring.dockerfile
    container_name: course_authoring_modules
    working_dir: /scrowl-project
    tty: true
    volumes:
      - './package.json:/scrowl-project/package.json'
      - './apps/course-authoring/package.json:/scrowl-project/apps/course-authoring/package.json'
      - './packages/config/package.json:/scrowl-project/packages/config/package.json'
      - './packages/typings/package.json:/scrowl-project/packages/typings/package.json'
      - 'shared_data:/scrowl-project'
    networks:
      - scrowl-network

  # This service has a non-root user (Electron app requirement).
  # Which mean this container cannot be used to update node modules.
  # Electron app development happens in this container
  course_authoring:
    user: node
    env_file:
      - apps/course-authoring/.env
    environment:
      # Fixes sockets on Docker on macOS. Using the container host for xhost
      # https://gist.github.com/paul-krohn/e45f96181b1cf5e536325d1bdee6c949
      - DISPLAY=host.docker.internal:0
      - DEBUG_ELECTRON_NODE=9000
      - DEBUG_ELECTRON_REACT=3000
    container_name: course_authoring
    build:
      context: .
      dockerfile: ./.docker/course-authoring.dockerfile
    working_dir: /scrowl-project
    security_opt:
      # workaround to running headless chrome from container
      # https://stackoverflow.com/a/53975412/15077454
      - seccomp=./apps/course-authoring/chrome.json
    command: >
      sh -c "npx yarn run start:tool:course"
    ports:
      - '9001:9000'
    volumes:
      - './package.json:/scrowl-project/package.json:ro'

      # adding VS Code launch file
      - './.vscode:/scrowl-project/.vscode'

      # adding electron app files
      - './apps/course-authoring/package.json:/scrowl-project/apps/course-authoring/package.json:ro'
      - './apps/course-authoring/src:/scrowl-project/apps/course-authoring/src'
      - './apps/course-authoring/tsconfig.json:/scrowl-project/apps/course-authoring/tsconfig.json'

      # adding config files
      - './packages/config/eslint-preset.js:/scrowl-project/packages/config/eslint-preset.js'
      - './packages/config/linters:/scrowl-project/packages/config/linters'
      - './packages/config/package.json:/scrowl-project/packages/config/package.json:ro'

      # adding tsconfig files
      - './packages/typings/package.json:/scrowl-project/packages/typings/package.json:ro'
      - './packages/typings:/scrowl-project/packages/typings'
    networks:
      - scrowl-network

networks:
  scrowl-network:
    driver: bridge
