version: "3.9"

volumes:
  shared_data:

services:

  # This service has Docker's defualt user.
  # Which mean this container is used to update node modules.
  scrowl_modules:
    image: docker.io/sezarosg/electron_app:latest
    # image: scrowl_modules
    # build:
    #   dockerfile: ./.docker/electron.dockerfile
    #   context: .
    container_name: scrowl_modules
    working_dir: /scrowl-project
    tty: true
    volumes:
       - "./package.json:/scrowl-project/package.json"
       - "./apps/electron/package.json:/scrowl-project/apps/electron/package.json"
       - "./packages/config/package.json:/scrowl-project/packages/config/package.json"
       - "./packages/tsconfig/package.json:/scrowl-project/packages/tsconfig/package.json"
       - "./packages/ui/package.json:/scrowl-project/packages/ui/package.json"
       - "shared_data:/scrowl-project"

    networks:
      - scrowl-network

  # This service has a non-root user (Electron app requirement).
  # Which mean this container cannot be used to update node modules.
  # Electron app development happens in this container
  scrowl:
    user: node
    env_file:
      - apps/electron/.env
    environment:
      # Fixes sockets on Docker on macOS. Using the container host for xhost
      # https://gist.github.com/paul-krohn/e45f96181b1cf5e536325d1bdee6c949
      - DISPLAY=host.docker.internal:0
      - DEBUG_ELECTRON_NODE=9000
      - DEBUG_ELECTRON_REACT=3000
    container_name: scrowl_electron
    image: docker.io/sezarosg/electron_app:latest
    working_dir: /scrowl-project
    security_opt:
      # workaround to running headless chrome from container
      # https://stackoverflow.com/a/53975412/15077454
      - seccomp=./apps/electron/chrome.json
    command: >
      sh -c "ls -al ./apps/electron/webpack && npx yarn turbo run start"
    ports:
      - "9001:9000"
    volumes:
      # adding shared volums (has access to all of the package.json files)
      - "shared_data:/scrowl-project"
      # adding VS Code launch file
      - "./.vscode:/scrowl-project/.vscode"

      # adding electron app files
      - "./apps/electron/package.json:/scrowl-project/apps/electron/package.json:ro"
      - "./apps/electron/src:/scrowl-project/apps/electron/src"
      - "./apps/electron/webpack:/scrowl-project/apps/electron/webpack"
      - "./apps/electron/tsconfig.json:/scrowl-project/apps/electron/tsconfig.json"
      - "./apps/electron/preload.js:/scrowl-project/apps/electron/preload.js"

      # adding config files
      - "./packages/config/eslint-preset.js:/scrowl-project/packages/config/eslint-preset.js"
      - "./packages/config/linters:/scrowl-project/packages/config/linters"
      - "./packages/config/package.json:/scrowl-project/packages/config/package.json:ro"

      # adding tsconfig files
      - "./packages/tsconfig/package.json:/scrowl-project/packages/tsconfig/package.json:ro"
      - "./packages/tsconfig:/scrowl-project/packages/tsconfig"

      # adding ui files
      - "./packages/ui/package.json:/scrowl-project/packages/ui/package.json:ro"
      - "./packages/ui/src:/scrowl-project/packages/ui/src"
      - "./packages/ui/tsconfig.json:/scrowl-project/packages/ui/tsconfig.json"
    networks:
      - scrowl-network

networks:
  scrowl-network:
    driver: bridge
