version: "3.9"
services:
  scrowl:
    environment:
      # Fixes sockets on Docker on macOS. Using the container host for xhost
      # https://gist.github.com/paul-krohn/e45f96181b1cf5e536325d1bdee6c949
      - DISPLAY=host.docker.internal:0
    container_name: electron
    build:
      dockerfile: ./.docker/node.dockerfile
      context: .
    image: scrowl_image
    working_dir: /app
    security_opt:
      # workaround to running headless chrome from container
      # https://stackoverflow.com/a/53975412/15077454
      - seccomp=./chrome.json
    command: >
      sh -c "
        npx yarn start"
    ports:
      - "9001:9000"
    volumes:
      - "./src:/app/src"
      - "./package.json:/app/package.json"
      - "./webpack:/app/webpack"
      - "./tsconfig.json:/app/tsconfig.json"
      - "./preload.js:/app/preload.js"
    networks:
      - scrowl-network

networks:
  scrowl-network:
    driver: bridge