name: deploy-pages
on: workflow_dispatch

jobs:
  deploy-pages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2

      - name: Get Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Lockfile
        uses: actions/cache@v3
        id: yarn-cache-lockfile
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Cache Modules
        uses: actions/cache@v3
        id: yarn-cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Pages
        run: yarn run build:downloads

      - name: Publish Github Page
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: apps/app-downloads/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}