name: release
on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@master
        with:
          node-version: 16.9

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install Lerna
        run: yarn add lerna -W -D

       - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn run lerna bootstrap

      - name: Publish Distributables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package:tool:course
