name: Release Workflow

on:
  release:
    types: [created]
  pull_request:
    branches: [main, develop]
    types: [closed]
  workflow_dispatch: # so we can run this workflow manually as well

jobs: 
  release:
    if: github.event_name != 'release' && github.ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: build
      